# Generated by Django 5.1.5 on 2025-01-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(upload_to='assets'),
        ),
    ]
