# Generated by Django 5.1.5 on 2025-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_image_alter_announcement_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='assets'),
        ),
    ]
