# Generated by Django 5.1.5 on 2025-01-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_residentialid_customuser_profile_delete_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
